<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<#include "parts/header.ftlh">
<div style="margin-top: 200px; margin-bottom: 200px; text-align: center; color: #1eaaf1; font-size: 50px">
    <p><strong>Что-то пошло не так</strong></p>
</div>
<#include "parts/footer.ftlh">
</body>
</html>