<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<#include "parts/header.ftlh">
<div id="colorlib-page">
    <div class="container">
        <div class="row">
            <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
            <aside id="colorlib-aside" role="complementary" class="text-center">
                <h1 id="colorlib-logo"><a href="index.html"><span class="img"
                                                                  style="background-image: url(img/teacher-1.jpg);"></span></a>
                </h1>
                <nav id="colorlib-main-menu" role="navigation">
                    <ul>
                        <li ><a href="/profile">Обо мне</a></li>
                        <li class="colorlib-active"><a href="/my_students">Мои студенты</a></li>
                    </ul>
                </nav>
            </aside> <!-- END COLORLIB-ASIDE -->
            <div id="colorlib-main">
                <section class="ftco-section-no-padding bg-light">
                    <div class="hero-wrap" style="background-color: #fff ! important">
                        <div class="overlay"></div>
                        <div class="d-flex align-items-center ">
                            <div class="author-info text p-3 p-md-5">
                                <div class="desc">
                                    <div style="text-align: center">
                                        <h1 class="big-letter"> 11-802</h1>
                                    </div>
                                    <div class="col-12 col-md-12 col-lg-12">
                                        <div class="shop_grid_product_area">

                                            <div class="row">

                                                <section class="ftco-section" style="padding: 0 0 ! important">
                                                    <div class="container">
                                                        <div class="row">
                                                            <div class="col-md-12 course d-lg-flex ftco-animate" style="margin-top: 20px; ">
                                                                <div class="img" style="background-image: url(img/student-1.jpg);"></div>
                                                                <div class="text bg-light p-4">
                                                                    <h3><a href="#">Рябов Дмитрий Александрович</a></h3>
                                                                    <p class="subheading">2 курс</p>
                                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia
                                                                        lectus sit amet pretium fermentum...</p>
                                                                    <input type="submit" value="Java" class="btn btn-secondary but">
                                                                    <input type="submit" value="Spring Boot"
                                                                           class="btn btn-secondary disabled but">
                                                                    <input type="submit" value="Jsoup" class="btn btn-secondary but">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-12 course d-lg-flex ftco-animate" >
                                                                <div class="img" style="background-image: url(img/student-2.jpg);"></div>
                                                                <div class="text bg-light p-4">
                                                                    <h3><a href="#">Хайруллина Камилла Альбертовна</a></h3>
                                                                    <p class="subheading">2 курс</p>
                                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia
                                                                        lectus sit amet pretium fermentum...</p>
                                                                    <input type="submit" value="Java" class="btn btn-secondary but">
                                                                    <input type="submit" value="Spring" class="btn btn-secondary disabled but">
                                                                    <input type="submit" value="PostgeSQL"
                                                                           class="btn btn-secondary disabled but">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-12 course d-lg-flex ftco-animate" >
                                                                <div class="img" style="background-image: url(img/student-3.jpg);"></div>
                                                                <div class="text bg-light p-4">
                                                                    <h3><a href="#">Богомолов Даниил Сергеевич</a></h3>
                                                                    <p class="subheading">2 курс</p>
                                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia
                                                                        lectus sit amet pretium fermentum...</p>
                                                                    <input type="submit" value="Java" class="btn btn-secondary but">
                                                                    <input type="submit" value="Spring Boot" class="btn btn-secondary but">
                                                                    <input type="submit" value="Spring Security"
                                                                           class="btn btn-secondary disabled but">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-12 course d-lg-flex ftco-animate" >
                                                                <div class="img" style="background-image: url(img/student-4.jpg);"></div>
                                                                <div class="text bg-light p-4">
                                                                    <h3><a href="#">Исаичкин Данила Алексеевич</a></h3>
                                                                    <p class="subheading">2 курс</p>
                                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia
                                                                        lectus sit amet pretium fermentum...</p>
                                                                    <input type="submit" value="Java" class="btn btn-secondary but">
                                                                    <input type="submit" value="Spring Boot" class="btn btn-secondary but">
                                                                    <input type="submit" value="Spring Cloud" class="btn btn-secondary but">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </section>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div><!-- END COLORLIB-MAIN -->
</div><!-- END COLORLIB-PAGE -->
<#include "parts/footer.ftlh">
</body>
</html>